# Generated by Django 2.1.3 on 2018-12-23 14:37

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iletisim_isim', models.CharField(max_length=100, verbose_name='İletişim Talep Edenin Adı')),
                ('iletisim_konu', models.CharField(max_length=100, verbose_name='İletişim Talebinin Konusu')),
                ('iletisim_ulasim', models.CharField(max_length=100, verbose_name='Ulaşım Adresi')),
                ('iletisim_mesaj', models.TextField(verbose_name='Mesaj')),
                ('iletisim_tarih', models.DateField(verbose_name='Mesaj Tarihi')),
            ],
            options={
                'ordering': ('-iletisim_tarih',),
            },
        ),
        migrations.CreateModel(
            name='Makaleler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makale_baslik', models.CharField(max_length=150, verbose_name='Makale Başlığı')),
                ('makale_yayintarihi', models.DateField(verbose_name='Makale Yayın Tarihi')),
                ('makale_mesaj', ckeditor.fields.RichTextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-makale_yayintarihi',),
            },
        ),
        migrations.CreateModel(
            name='Notlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_isim', models.CharField(max_length=150, verbose_name='Not Bırakanın İsmi')),
                ('not_mail', models.CharField(max_length=100, verbose_name='Not Bırakanın Maili')),
                ('not_mesaj', models.TextField(verbose_name='Not Bırakanın Mesajı')),
                ('not_tarih', models.DateTimeField(auto_now_add=True, verbose_name='Not Bırakılma Tarihi')),
            ],
            options={
                'ordering': ('-not_tarih',),
            },
        ),
        migrations.CreateModel(
            name='Randevular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('randevu_isim', models.CharField(max_length=100)),
                ('randevu_ulasim', models.CharField(max_length=100, verbose_name='İletişim Adresi')),
                ('randevu_tarih', models.CharField(max_length=100, verbose_name='Talep Edilen Randevu Tarihi')),
                ('randevu_saat', models.CharField(max_length=100, verbose_name='Talep Edilen Randevu Saati')),
                ('randevu_mesaj', models.TextField(verbose_name='Mesaj')),
            ],
            options={
                'ordering': ('-randevu_tarih',),
            },
        ),
    ]
