# Generated by Django 2.1.3 on 2018-12-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitesi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactform',
            options={'ordering': ('-iletisim_tarih',), 'verbose_name': 'İletişim Talebi', 'verbose_name_plural': 'İletişim Talepleri'},
        ),
        migrations.AlterModelOptions(
            name='makaleler',
            options={'ordering': ('-makale_yayintarihi',), 'verbose_name': 'Makale', 'verbose_name_plural': 'Makaleler'},
        ),
        migrations.AlterModelOptions(
            name='notlar',
            options={'ordering': ('-not_tarih',), 'verbose_name': 'Not', 'verbose_name_plural': 'Notlar'},
        ),
        migrations.AlterModelOptions(
            name='randevular',
            options={'ordering': ('-randevu_tarih',), 'verbose_name': 'Randevu', 'verbose_name_plural': 'Randevular'},
        ),
        migrations.AddField(
            model_name='makaleler',
            name='makale_slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
